### ISSUE TITLE
Timestamps and reference clocks

### ISSUE THREAD

**Issue by ingararntzen** [webtiming/timingobject#16]
There are currently some issues in the spec with respect to definition of timestamps and what clocks they are sampled from.

The main requirement is that there is agreement on what clock is being used by timing provider and timing object. In addition this clock must be available directly to the application using the timing object so that timestamps may make sense also externally to the timing object. Also, it should be known how this clock relates to epoch - new Date().getTime(). Finally, the clock should ideally be sub-millisecond and monotonic.

The HR-time (performance) gives us all of this, and the browser support seems to be quite good already [1]  I think we should simply require the use of this clock.

~~This would mean that the timing provider does not have to provide a now() function. It is simply responsible for delivering state vectors that are timestamped with the HR clock. This is also true for online timing providers - they must translate from the clock used by the online timing service into the HR-time clock which is client-specific.~~

One little thing to note - HR-time - performance.now() gives timestamp values where the unit is milliseconds. The timing object defines it rates velocity and acceleration as unit change per second. This is nice I think - because the timing object is often used to represent rate-change phenomena in the human realm.

I'll start updating the spec accordingly.

[1] http://caniuse.com/#feat=nav-timing

**Comment by ingararntzen** [comment]
By the way, a consequence of using HR-time as clock is that there will be a lot of negative timestamps when working with online timing resources. This is because online timing resources existed before the page was loaded - when HR-time starts counting from 0 ms. This is not a problem though - but maybe a bit puzzling at first.

**Comment by tidoust** [comment]
+1 for requiring the use of the High Resolution Time clock where possible.

However, I confess I'm a bit at a loss when it comes to dropping the `now()` function. If you drop the `now()` function, wouldn't the timing provider's code need to adjust the parameters (e.g. velocity) of the state vector on a regular basis to adjust the clock used by the online timing service with the local HR clock? In turn, that would generate a number of fake (in the sense that they would not correspond to any real vector update) events.

I thought the goal was rather to expose the same state vector to all clients, and let the user agent adjust its internal clock to that imposed by the timing provider. What did I miss?

**Comment by ingararntzen** [comment]
+1 for being completely right and covering my back.

my bad - please ignore paragraph about removing .now() function of timing provider.

I thought for a moment that the now() function was equal to performance.now() - which it isn't

looking a bit into the details of the spec - I would like to suggest an alternative approach from what is currently described

here's my thinking:

to process a query on the timing object we essentially need  two timestamps
- ts_now
- ts_init - from initial vector
  as we are going to subtract them it does not really matter what clock these values are sampled from (as long as it is the same clock).
  however - the query method will return ts_now to the application - so this should be a value sampled from performance.now().

It follows that what we need from the timing provider is a fresh evaluation of ts_init - translated onto to timeline of HR-time/performance.now().

Therefore - the query method of the timing object will use
vector.position, vector.velocity and vector.acceleration from the timing provider initial vector
vector.timestamp should not be used (should not even be exposed to the timing object)
instead the timing provider provides a method .timestamp() that should be used instead in order to fetch the t_init.

.timestamp() then represents the current estimate for t_init (when the initial vector was defined) - translated onto the timeline of performance.now() - (this is typically a negative number) - but it should be quite stable - change only a few milliseconds back and forth (during periods short enough for clock drift to be negligible).  

Furthermore, I also suggest that all timestamps used throughout timing provider and timing object are given in milliseconds  - not seconds.

**Comment by tidoust** [comment]
Hmmm, this probably amounts to the same result in the end and thus it may be just a matter of taste, but I find it much more intuitive to ask the timing provider for an evaluation of the current time than to ask it for an evaluation of when a past event occurred (or perhaps more accurately for an evaluation of when a past event should be seen as having occurred to be able to compute the proper elapsed number of milliseconds).

I would rather keep `ts_init` constant in your example: it is the timing provider's evaluation of when the initial vector was set. When that evaluation was made, it was as accurate as possible, even though clocks may have drifted since then, so I don't see why it should change over time.

And I would thus ask the timing provider for an evaluation of `ts_now`. That's what the `now()` method does. This way, it exposes the software clock that the timing provider needs to maintain and keep in sync with the server clock. The user agent would then synchronize its internal software clock with this clock using any "usual" clock synchronization mechanism.

If the timing provider fails to implement a monotonic clock, the user agent could also use that synchronization opportunity to fix that (instead of throwing an `OperationError` as currently defined in the spec). Said differently, I would let the user agent handle the mapping between the clock exposed by the timing provider and the `performance.now()` timeline.

Actually, the time origin used by the timing provider does not even really matter (so values it reports do not necessarily have to be on the timeline of the `performance.now()` clock) since we're really just interested in computing differences between two timestamps.

Do you see any notable advantages or drawbacks with either approach?

**Comment by ingararntzen** [comment]
Hi Francois. 

I think you have managed to convince me that your proposal is more intuitive :)

My suggestion was based on the "need to know" principle that the user agent should not have to know about the timeline used by the timing provider since it strictly does not have to.

I quite agree though that a floating t_init is somewhat weird concept - even if the math is correct.

With your suggestion - the useragent gets both t_init and t_now in the provider timeline. This is enough for calculating the diff, but as the timingobject.query() operation should return timestamps from the performance.now timeline,  t_now from the timing provider needs to be translated. 

I think the easiest solution would be if timingprovider did this translation as part of its .now() method.

ts_now_provider <- timingprovider.now(ts_now_useragent)

timingprovider.now() takes a timestamp from useragent timeline as parameter and returns corresponding timestamp from timingprovider timeline. (maybe "now" isn't the correct name any more)

I see your point of simply exposing the clock of the timing provider, and then let the useragent manage its own clock and synchronize it with the provider clock. This gives more flexibility to the user agent. I'm a bit worried though that having two clock-sync processes (first timing provider and then user agent) instead of just one might make the end result less precise. The errors from the first should dominate errors from the second - but I don't have the competence to say for sure if this is completely safe.

In the interest of airing all possibilities; it would also be possible to avoid clock sync completely in the timing provider, and instead have it simply relay request-response messages on behalf of the clock sync algorithm running in the user agent. I suppose this would limit the design space for timing providers.

What do you think?

Njål also pointed out another thing to consider. The query operation needs to be very cheap - and ideally it should be able to complete without consulting the timingprovider at all, as it may be running in a different thread. This is possible in your approach. It would also be possible if the timing provider provides the skew as an observable property.

And another thing.

How about the timing provider object managing N timing resources instead of just one?

**Comment by tidoust** [comment]
Ah, I'm glad to see that my intuitions can be contagious ;)

Reacting on your specific suggestions:

>  t_now from the timing provider needs to be translated. I think the easiest solution would be if timingprovider did this translation as part of its .now() method.

That matches what I had initially started to specify, but I think "easiest" should apply to the timing provider side in the end, not to the user agent. What I mean by that:
1. The interface and requirements that timing providers need to follow should remain as simple as possible, because we will have less control on timing providers: there will be more of them that may not be around the table when the spec is standardized, and allowing "regular" (non sync experts) Web app developers to act as timing providers sounds like a good thing, even though the result may not be that good in terms of actual synchronization.
2. The user agent cannot trust the code provided by timing providers by definition: it will have to add a layer on top of that code to ensure that it can trap (and/or possibly fix) whatever error timing provider code may make, typically failures to respect clock monotonicity.
3. The internal clock(s) used by the user agent would likely run in another thread (and in another runtime) as Njål pointed out, so the user agent will need to synchronize these clocks with the timing provider one way no matter what, to be able to respond to compute the current state vector whenever it needs to without having to run the timing provider code.

Does the user agent need to now how a timing provider timeline map to the `performance.now()` timeline by the way? I guess the user agent could call `now()` when the timing object is first connected to the timing provider object and use that initial mapping as reference to relate further timestamps of the timing provider to the `performance.now()` timeline.

> I'm a bit worried though that having two clock-sync processes (first timing provider and then user agent) instead of just one might make the end result less precise. The errors from the first should dominate errors from the second - but I don't have the competence to say for sure if this is completely safe.

Right, I wondered about that as well. I guess we'll have to wait for concrete feedback from implementers. I don't have the competence either :)

> In the interest of airing all possibilities; it would also be possible to avoid clock sync completely in the timing provider, and instead have it simply relay request-response messages on behalf of the clock sync algorithm running in the user agent. I suppose this would limit the design space for timing providers.

Yes, that's an option. It requires agreeing on a particular clock synchronization mechanism: those I reviewed seem to be all alike, doing the same computation based on the round trip time... and all different when you look into details, for instance the backend may push additional sync messages on its own, or the client may send a batch of requests and discard the ones that take too long. I would keep the idea in the back of our minds until we need it.

> How about the timing provider object managing N timing resources instead of just one?

I suppose that it would depend on how the user agent would implement the feature but it could well maintain only one clock internally shared by the different timing objects connected to the same timing provider object. Did you have specific worries on that front?

I note that the idea to require the timing provider code to run in a separate JavaScript realm (see issue #10) would make it next to impossible to reuse the same timing provider object across timing objects, unless we have chaining (see issue #13).

**Comment by ingararntzen** [comment]
Hi again Francois

Here's a concrete suggestion that I think address your concern for simplicity on the client provider side.

The timing provider simply exposes (change whenever it does change)
.vector 
.skew - fresh estimate on diff between provider timeline and user agent timeline (HR-TIME)

(I'm assuming that HR-TIME is available to all parties involved)

That's all. This pushes the responsibility onto the timingobject for smoothing the sudden effects of changes to skew to ensure monotonic (it even opens up for a possible onskewchange event )

The timing object then implements software clock by using vector[_init], skew and some linearly decreasing smoothing effect. As a result it can always resolve queries without consulting with the timing provider object.

Is this good, or did I miss something now?

**Comment by tidoust** [comment]
This time, I think you have managed to convince me that your proposal is better! ;)

It looks good, would indeed avoid the double clock-sync process, and would actually simplify the work for the timing provider!

I don't think that we should add a "skewchange" event on the TimingObject interface today, unless you have a specific use case in mind that would require it. It may not mean much, in the sense that the smoothing effect could mean that the skew reported by the timing provider may not exactly match the skew of the timing object's software clock.

**Comment by ingararntzen** [comment]
Excellent!
- and its simple to explain too :)

I'll update the spec shortly.

No, I didn't have a specific use case in mind. The point would be to give timed component a little nudge so that they can immediately re-evaluate their time-alignment with the timing object. I don't see the necessity though. For instance, I think the sequencer implementation is resilient to both abrupt skew changes and non-monotonic behavior.

**Comment by ingararntzen** [comment]
This discussion is now reflected in the spec
